/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesSocialMediaRouteImport } from './routes/services.social-media'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesReportingRouteImport } from './routes/services.reporting'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services.google-ads'
import { Route as ServicesContentRouteImport } from './routes/services.content'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/website-development',
    path: '/website-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSocialMediaRoute = ServicesSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesReportingRoute = ServicesReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesContentRoute = ServicesContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ServicesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/content': typeof ServicesContentRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/reporting': typeof ServicesReportingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/content': typeof ServicesContentRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/reporting': typeof ServicesReportingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/content': typeof ServicesContentRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/reporting': typeof ServicesReportingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/services/content'
    | '/services/google-ads'
    | '/services/reporting'
    | '/services/seo'
    | '/services/social-media'
    | '/services/website-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/services/content'
    | '/services/google-ads'
    | '/services/reporting'
    | '/services/seo'
    | '/services/social-media'
    | '/services/website-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/services/content'
    | '/services/google-ads'
    | '/services/reporting'
    | '/services/seo'
    | '/services/social-media'
    | '/services/website-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media': {
      id: '/services/social-media'
      path: '/social-media'
      fullPath: '/services/social-media'
      preLoaderRoute: typeof ServicesSocialMediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/reporting': {
      id: '/services/reporting'
      path: '/reporting'
      fullPath: '/services/reporting'
      preLoaderRoute: typeof ServicesReportingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content': {
      id: '/services/content'
      path: '/content'
      fullPath: '/services/content'
      preLoaderRoute: typeof ServicesContentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesContentRoute: typeof ServicesContentRoute
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesReportingRoute: typeof ServicesReportingRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaRoute: typeof ServicesSocialMediaRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesContentRoute: ServicesContentRoute,
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesReportingRoute: ServicesReportingRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaRoute: ServicesSocialMediaRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
